/*******************************************************************************
 * JC8012P4A1C LVGL 9.3 Squareline Launcher
 *
 * For the Guition JC8012P4A1C ESP32-P4 LCD (800x1280 JD9365 MIPI-DSI panel +
 * GSL3680 capacitive touch).  Display rotation is done by the ESP32-P4 PPA
 * in hardware.
 *
 * Demonstrates touchscreen, LVGL 9.3 and a SquareLine Studio UI.
 *
 * Orientation: lv_setup.begin(rotation) accepts 0 = portrait (800x1280, the
 * panel's native orientation), 1 = landscape (1280x800), 2 = portrait flipped,
 * 3 = landscape flipped (degrees 90/180/270 work as aliases for 1/2/3).  This
 * sketch defaults to portrait; change the argument below to rotate.  Display
 * and touch rotate together.  Size your SquareLine project to match the
 * orientation you choose:
 *   portrait  rotation 0 or 2  ->  800x1280
 *   landscape rotation 1 or 3  ->  1280x800
 *
 * Requires the following libraries:
 *   - chipguy_JC8012P4A1C_display  (display + touch driver, this library)
 *   - lvgl 9.3
 *
 * Arduino IDE Board Settings:
 *   - Board: ESP32P4 Dev Module
 *   - PSRAM: OPI PSRAM   (REQUIRED — the driver allocates its buffers in PSRAM)
 *   - Flash Size: 16 MegaBytes (128 megabits)
 *   - USB CDC On Boot: Enabled
 *
 ******************************************************************************/

// This is built for LVGL 9.3, which SquareLine can generate UIs for.
// It's important for the version numbers to match, even if it's not newest.
#include "lv_conf.h"
#include "lvgl.h"
#include "lv_setup.hpp"

// The folder of UI files generated by SquareLine should be in a subdirectory
// named src in the sketch folder.  The existing files are a small example.
// Simply DELETE all of the example files, and "Export" new "UI files", from
// SquareLine.  Using the "Arduino TFT_eSPI profile" works (among others).
// Required SquareLine project settings: 16-bit color depth, no rotation or
// offset (this library handles rotation, so keep the SquareLine project
// unrotated).  Size the project to match the rotation chosen in setup() below:
//   portrait  rotation 0 or 2  ->  800x1280
//   landscape rotation 1 or 3  ->  1280x800
#include "src/ui.h"

void setup() {
    // On the ESP32-P4 the USB serial port is Serial0; "USB CDC On Boot" must be
    // enabled in the Tools menu to see this output.
    Serial0.begin(115200);

    // Initialize display, touch, and LVGL.  Defaults to portrait; pass a
    // rotation to change it (0/2 = portrait, 1/3 = landscape; see header).
    // Match the SquareLine project size to this choice (see the note above).
    lv_setup.begin();
    Serial0.printf("LVGL initialized with %dx%d touchscreen\n",
                   display.width(), display.height());

    // Start the SquareLine application's own setup
    ui_init();
}

void loop() {
    // Give loop control to LVGL objects created by the SquareLine application
    lv_timer_handler();
    delay(5);
}
